#ifndef AFTERMATH_LIBJIMAGE_BIND_AFTERMATH_LIBJIMAGE_BIND_H
#define AFTERMATH_LIBJIMAGE_BIND_AFTERMATH_LIBJIMAGE_BIND_H

extern "C" int get_modules();

#endif // AFTERMATH_LIBJIMAGE_BIND_AFTERMATH_LIBJIMAGE_BIND_H
